const API='http://127.0.0.1:5095';
const options={standard:{label:'统一标准',conditions:[],fields:[]},
  'product-trace':{label:'产品追溯',conditions:[['sn','SN']],fields:[['sn','SN'],['status','状态'],['modelCode','型号'],['moNumber','工单'],['projectNo','项目'],['quantity','数量'],['firstInTime','首次过站'],['lastInTime','最后过站'],['errorRecords','异常记录'],['ngQuantity','NG 数量'],['reworkRecords','返工记录'],['scrapQuantity','报废数量']]},
  capacity:{label:'产能',conditions:[['dateRange','日期范围']],fields:[['passRecords','过站记录'],['serials','参与 SN'],['completedSerials','完成 SN'],['errorRecords','异常记录'],['ngQuantity','NG 数量'],['activeDays','有效生产天数'],['averageCompletedPerActiveDay','日均完成 SN']]}
};
let reports=[],selectedId=null,sqlParameters=[],sqlColumns=[],layoutWidgets=[];const $=s=>document.querySelector(s);const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function filtered(){const q=$('#search-reports').value.trim().toLowerCase(),category=$('#filter-category').value;return reports.filter(r=>(!category||r.category===category)&&(!q||r.name.toLowerCase().includes(q)||r.category.toLowerCase().includes(q)));}
function renderList(){const rows=filtered();$('#report-list').innerHTML=rows.map(r=>`<tr><td class="name-cell"><strong>${esc(r.name)}</strong><span>${esc(r.id)}</span></td><td>${esc(r.category)}</td><td><span class="type-tag">${options[r.queryType].label}</span></td><td>${r.conditions.map(c=>options[r.queryType].conditions.find(x=>x[0]===c)?.[1]??c).join('、')||'—'}</td><td>${r.displayFields.length} 个字段</td><td><span class="status-tag">${r.enabled?'已发布':'草稿'}</span></td><td class="actions-cell"><button class="link-button" data-edit="${esc(r.id)}">编辑</button><button class="link-button" data-copy="${esc(r.id)}">复制</button></td></tr>`).join('');$('#empty-list').hidden=rows.length>0;document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openEditor(b.dataset.edit)));document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',()=>copyReport(b.dataset.copy)));}
function renderCategories(){const selected=$('#filter-category').value;const categories=[...new Set(reports.map(r=>r.category))].sort();$('#filter-category').innerHTML=`<option value="">全部分类</option>${categories.map(c=>`<option ${c===selected?'selected':''}>${esc(c)}</option>`).join('')}`;}
function showPage(page){$('#report-list-page').hidden=page!=='list';$('#editor-page').hidden=page!=='editor';$('#breadcrumb').textContent=page==='list'?'报表管理':'报表管理 / 配置报表';}
function checkOptions(kind,selected=[]){const fromSql=kind==='conditions'?sqlParameters:sqlColumns;if(fromSql.length)return fromSql.map(id=>`<label><input type="checkbox" value="${esc(id)}" ${selected.includes(id)?'checked':''}>${esc(id)}</label>`).join('');return options[$('#definition-query-type').value][kind].map(([id,label])=>`<label><input type="checkbox" value="${id}" ${selected.includes(id)?'checked':''}>${label}</label>`).join('');}
function refreshOptionPanels(report){$('#condition-options').innerHTML=checkOptions('conditions',report?.conditions);$('#field-options').innerHTML=checkOptions('fields',report?.displayFields);}
function ensurePresentationSettings(){const grid=document.querySelector('[data-panel="basic"] .form-grid');if(!$('#definition-style'))grid.insertAdjacentHTML('beforeend','<label>展示样式<select id="definition-style"><option value="standard">标准表格</option><option value="compact">紧凑表格</option></select><small>统一报表结果的表格密度。</small></label><label><span>结果导出</span><span><input id="definition-export-csv" type="checkbox" checked> 显示“导出 CSV”按钮</span><small>关闭后业务前端不显示导出按钮。</small></label>');if(!$('#layout-config'))grid.insertAdjacentHTML('afterend','<section id="layout-config" style="margin-top:22px"><h2>仪表盘布局</h2><p class="hint">拖拽组件调整顺序；宽度按 12 栅格设置。</p><div><button type="button" class="secondary" data-add-widget="metric">+ 指标卡</button> <button type="button" class="secondary" data-add-widget="bar">+ 柱状图</button> <button type="button" class="secondary" data-add-widget="line">+ 折线图</button></div><div id="layout-widgets" class="option-grid" style="margin-top:12px"></div></section>');document.querySelectorAll('[data-add-widget]').forEach(b=>b.onclick=()=>{layoutWidgets.push({id:crypto.randomUUID(),type:b.dataset.addWidget,title:b.dataset.addWidget==='metric'?'指标卡':b.dataset.addWidget==='bar'?'柱状图':'折线图',width:6});renderLayoutWidgets();});}
function renderLayoutWidgets(){const holder=$('#layout-widgets');if(!holder)return;holder.innerHTML=layoutWidgets.map((w,i)=>`<div draggable="true" data-widget-index="${i}" style="border:1px solid #d0d5dd;border-radius:6px;padding:10px"><b>☰ ${esc(w.title)}</b><br><small>${esc(w.type)} · 宽度</small> <select data-width="${i}"><option ${w.width===3?'selected':''} value="3">3</option><option ${w.width===6?'selected':''} value="6">6</option><option ${w.width===9?'selected':''} value="9">9</option><option ${w.width===12?'selected':''} value="12">12</option></select> <button type="button" data-remove="${i}">删除</button></div>`).join('')||'<p class="hint">未添加组件时，前端会使用默认组件。</p>';holder.querySelectorAll('[data-width]').forEach(x=>x.onchange=()=>layoutWidgets[+x.dataset.width].width=+x.value);holder.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{layoutWidgets.splice(+x.dataset.remove,1);renderLayoutWidgets();});let from=null;holder.querySelectorAll('[draggable]').forEach(x=>{x.ondragstart=()=>from=+x.dataset.widgetIndex;x.ondragover=e=>e.preventDefault();x.ondrop=e=>{e.preventDefault();const to=+x.dataset.widgetIndex;if(from!==null&&from!==to){const [item]=layoutWidgets.splice(from,1);layoutWidgets.splice(to,0,item);renderLayoutWidgets();}};});}
function formData(){return{id:$('#definition-id').value.trim(),name:$('#definition-name').value.trim(),category:$('#definition-category').value.trim(),queryType:'standard',conditions:[...document.querySelectorAll('#condition-options input:checked')].map(x=>x.value),displayFields:[...document.querySelectorAll('#field-options input:checked')].map(x=>x.value),enabled:true,sqlText:$('#definition-sql').value.trim(),reportStyle:$('#definition-style').value,enableCsvExport:$('#definition-export-csv').checked,dashboardWidgets:layoutWidgets};}
ensurePresentationSettings();
renderLayoutWidgets();
function renderPreview(){const r=formData(),type=options[r.queryType];$('#preview').innerHTML=[['报表名称',r.name||'未命名报表'],['一级分类',r.category||'未设置'],['查询类型',type.label],['查询 SQL',r.sqlText?'已配置':'未配置'],['查询条件',r.conditions.map(id=>type.conditions.find(x=>x[0]===id)?.[1]).join('、')||'未选择'],['展示字段',r.displayFields.map(id=>type.fields.find(x=>x[0]===id)?.[1]).join('、')||'未选择'],['发布状态','保存后立即在业务前端生效']].map(([a,b])=>`<div class="preview-row"><span>${a}</span><strong>${b}</strong></div>`).join('');}
function activateTab(tab){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(x=>x.hidden=x.dataset.panel!==tab);if(tab==='preview')renderPreview();}
function openEditor(id=null){const r=reports.find(x=>x.id===id);selectedId=id;sqlParameters=[];sqlColumns=[];$('#report-form').reset();$('#definition-id').readOnly=!!r;$('#delete-report').hidden=!r;if(r){$('#editor-title').textContent=`编辑：${r.name}`;$('#definition-id').value=r.id;$('#definition-name').value=r.name;$('#definition-category').value=r.category;$('#definition-query-type').value=r.queryType;$('#definition-sql').value=r.sqlText||'';refreshOptionPanels(r);validateSql(true);}else{$('#editor-title').textContent='新建报表';refreshOptionPanels();}$('#message').textContent='';$('#sql-validation').textContent='';activateTab('basic');showPage('editor');}
function copyReport(id){const r=reports.find(x=>x.id===id);if(!r)return;openEditor();$('#definition-name').value=`${r.name} - 副本`;$('#definition-category').value=r.category;$('#definition-query-type').value=r.queryType;refreshOptionPanels(r);}
async function load(){const response=await fetch(`${API}/api/report-definitions`);if(!response.ok)throw new Error();reports=await response.json();$('#api-status').textContent='API 已连接';renderCategories();renderList();}
async function save(){const r=formData();if(!r.id||!r.name||!r.category){$('#message').textContent='请填写报表标识、名称和分类。';return;}const exists=reports.some(x=>x.id===r.id);const response=await fetch(`${API}/api/report-definitions${exists?`/${encodeURIComponent(r.id)}`:''}`,{method:exists?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)});const body=await response.json().catch(()=>({}));if(!response.ok){$('#message').textContent=body.message||'保存失败。';return;}await load();openEditor(r.id);$('#message').textContent='已保存，业务前端将读取最新配置。';}
async function validateSql(keepSelection=false){const sqlText=$('#definition-sql').value.trim(),target=$('#sql-validation');if(!sqlText){target.textContent='请先填写 SQL。';return;}const oldConditions=keepSelection?[...document.querySelectorAll('#condition-options input:checked')].map(x=>x.value):[];const oldFields=keepSelection?[...document.querySelectorAll('#field-options input:checked')].map(x=>x.value):[];target.textContent='正在校验…';const response=await fetch(`${API}/api/report-definitions/validate-sql`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sqlText})});const body=await response.json().catch(()=>({}));if(response.ok){sqlParameters=body.parameters||[];sqlColumns=body.columns||[];refreshOptionPanels({conditions:oldConditions.length?oldConditions:sqlParameters,displayFields:oldFields.length?oldFields:sqlColumns});target.textContent=`${body.message} 参数：${sqlParameters.join('、')||'无'}；字段：${sqlColumns.join('、')||'无'}`;}else target.textContent=body.message||'校验失败。';}
async function remove(){const id=$('#definition-id').value;if(!id||!confirm(`确定删除“${$('#definition-name').value}”吗？`))return;const response=await fetch(`${API}/api/report-definitions/${encodeURIComponent(id)}`,{method:'DELETE'});if(!response.ok){$('#message').textContent='删除失败。';return;}await load();showPage('list');}
$('#create-report').addEventListener('click',()=>openEditor());$('#back-to-list').addEventListener('click',()=>showPage('list'));$('#save-report').addEventListener('click',save);$('#delete-report').addEventListener('click',remove);$('#validate-sql').addEventListener('click',()=>validateSql(false));document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>activateTab(t.dataset.tab)));$('#search-reports').addEventListener('input',renderList);$('#filter-category').addEventListener('change',renderList);load().catch(()=>{$('#api-status').textContent='API 连接失败';});
